import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// Polices (tu gardes exactement ça, c’est parfait)
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// METADATA COMPLÈTE → c’est ÇA qui supprime "Create Next App"
export const metadata = {
  title: 'WIN SHOP - Shopping & Tech',
  description: 'Votre destination Shopping & Tech : téléphones, consoles, mode et bien plus encore.',

  // Ligne magique qui supprime "Generated by create next app"
  generator: 'WIN SHOP',

  // Infos générales
  applicationName: 'WIN SHOP',
  keywords: ['winshop', 'shopping', 'tech', 'téléphone', 'console', 'mode'],
  authors: [{ name: 'WIN SHOP' }],
  creator: 'WIN SHOP',
  publisher: 'WIN SHOP',

  // Open Graph → WhatsApp, Facebook, Messenger, iMessage…
  openGraph: {
    title: 'WIN SHOP',
    description: 'Votre destination Shopping & Tech',
    url: 'https://winshop.online',
    siteName: 'WIN SHOP',
    images: [
      {
        url: 'https://winshop.online/og-image.jpg', // tu pourras ajouter cette image plus tard
        width: 1200,
        height: 630,
        alt: 'WIN SHOP - Shopping & Tech',
      },
    ],
    locale: 'fr_FR',
    type: 'website',
  },

  // Twitter / X
  twitter: {
    card: 'summary_large_image',
    title: 'WIN SHOP',
    description: 'Votre destination Shopping & Tech',
    images: ['https://winshop.online/og-image.jpg'],
  },

  // Favicon (tu les as déjà dans /app)
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },

  manifest: '/manifest.json',
};

// Layout principal
export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
